# AI in FinTech: A Robo-Advisory Case Study

## Robo-Advisory Regulation: Recent Developments





## AI-driven processes
Consumers and investors are benefiting from both the emergence of new fintech solutions and the further development of existing financial service providers. This has led to a wider range of financial products and services being offered more efficiently and effectively, and companies are under competitive pressure to become more consumer-centric. However, the increasing use of fintech solutions and new technologies also entails risks to which regulators and supervisory authorities are reacting. In this chapter, we will first discuss and illustrate some AI-driven processes in the robo-advisory industry and illustrate the mechanism using pseudocodes to give the reader an understanding of how AI is driving this industry and, in some selected cases, also help develop a better understanding of which areas are affected by regulatory changes in practice. We then set out to analyze the impact of the regulations on startups, whether they are justified, whether they are really having the desired effect, and ultimately what impact they are having on the economy as a whole. To this end, we conducted several interviews with CEOs of fintech companies in Switzerland to obtain first-hand opinions from those most directly affected by the new regulations. Finally, we summarize these interviews in the last subchapter, which we will later refer to as "Voices from the Industry", where we ask Dr. Adriano Lucatelli, CEO and co-founder of Descartes Finance AG, Julian Liniger, CEO and co-founder of Relai AG, and Rino Borini, lecturer at HWZ and co-founder of Scarossa and House of Satosh, about their personal opinion of new regulations


## AI-driven Process
A robo-advisor is a digital construct that typically relies on algorithms and/or AI to provide financial advice to clients. Below, we attempt to illustrate some of the AI-driven process of robo-advisors to exemplify how AI is used in practice. We have created several pseudocode's in the Python language to illustrate the exact mechanism by which the robo-advisor categorizes the client and then finally creates an investment advice. Note that we have only used a very naive questionnaire, which in reality would not comply with the revised FinSA, as we do not distinguish between risk capacity and risk preference as this would be needed to prevent any oversteering of the risk profile. One way to do this would be to count the risk capacity and risk preference scores separately and then use the respective lower score in each case for the final risk category assignment. At the end we also included a pseudocode for the rebalancing.

### Risk categories
In the following exemplary code we define 5 different risk categeories with the respective investment strategy name of which one later the robo-advisor wil assign the client to.
```{python eval=FALSE}
# Defining risk categories
def investment_recommendation():
    risk_levels = {
            'Conservative': '80% bonds, 20% equities',
            'Balanced': '60% bonds, 40% equities',
            'Growth': '40% bonds, 60% equities',
            'Opportunistic': '20% bonds, 80% equities',
            'All Equity': '0% bonds, 100% equities',      
    }   
```

### Questionnaire
What we are currently seeing in the robo-advisor industry is that questionnaires are generally being shortened to make it even more attractive for new clients to start investing. On the other hand, enough questions need to be asked to correctly identify the client's risk capacity and risk preference in order to comply with regulations such as the FIDLEG. For simplicity, we have included 10 questions in the following pseudocode, which are inspired from several leading Swiss robo-advisors.

```{python eval=FALSE}
# Questions
class risk_profile(FlaskForm):
    
    q1 = RadioField("1. Please enter your age", 
    choices = [
      ('0', 'More than 60'),
      ('2', 'Between 51 and 60'), 
      ('5', 'Between 41 and 50'), 
      ('8', 'Between 31 and 40'), 
      ('10', '30 or younger')])
    q2 = RadioField("2. What is your investment horizon?", choices = [
      ('0', 'Within the next year'), 
      ('2', '2 - 5 years'), 
      ('5', '5 - 10 years'), 
      ('8', '10 - 20 years'), 
      ('10', 'More than 20 years')])
    q3 = RadioField("3. If you were to lose your job, how long would you be able to finance your current living?", 
    choices = [
      ('0', '1 week'), 
      ('2', '1 month'), 
      ('5', '3 months'), 
      ('8', '6 months or more'), 
      ('10', 'I am already retired')])
    q4 = RadioField("4. What is your total annual income?", choices = [
      ('0', 'Less than CHF 50,000'), 
      ('2', 'CHF 50,000 - CHF 100,000'), 
      ('5', 'CHF 100,000 - CHF 150,000'), 
      ('8', 'CHF 150,000 - CHF 250,000'), 
      ('10', 'More than CHF 250,000')])
    q5 = RadioField("5. How is the stability of your income", 
    choices = [
      ('0', 'Low'), 
      ('2', 'Below average'), 
      ('5', 'Average'), 
      ('8', 'Above Average'), 
      ('10', 'Very Stable')])
    q6 = RadioField("6. If you would receive CHF 20,000 today, what would you do?", 
    choices = [
      ('0', 'Deposit it in bank account'), 
      ('2', 'Invest only in safe bonds'), 
      ('5', 'Invest in a mix of bonds and stocks'), 
      ('8', 'Invest only in stockss'), 
      ('10', 'Buy a new car')])
    q7 = RadioField("7. When you think of the word “risk” in a financial context, which of the following words come to mind?", 
    choices = [
      ('0', 'Loss'), 
      ('2', 'Dangerous'), 
      ('5', 'Uncertainty'), 
      ('8', 'Opportunity'), 
      ('10', 'Thrill')])
    q8 = RadioField("8. Which of the following statements would best describe your attitude regarding investing?", 
    choices = [
      ('0', "I need to see a little return"), 
      ('2', "I would have a hard time tolerating any losses"), 
      ('5', "I can tolerate a small loss"), 
      ('8', "I can tolerate a loss"), 
      ('10', "I don't mind a loss at all")])
    q9 = RadioField("9. Throughout the 2009 financial crisis, the SMI lost 50% of its value. Which of the following would you have done if your portfolio experiences a 50% loss?", 
    choices = [
      ('0', 'Sell all investments'), 
      ('2', "Move all investments into bonds"), 
      ('5', 'Change to a more conservative allocation'), 
      ('8', 'Hold on to investments'), 
      ('10', "Investeven  more")]) 
    q10 = RadioField("10. As return increases so does risk. Which statement applies to you?", 
    choices = [
      ('0', "I am not willing to accept any fluctuations in value"), 
      ('2', "I can live with fluctuations between 0% to 5%"), 
      ('5', "Value fluctuations between 5% and 10% are fine"), 
      ('8', "I can accept fluctuations between 10% and 20%"), 
      ('10', "Even fluctuations over 20% are fine for me")])
```

### Point distribution
Here, our pseudocode classifies the customer into one of five risk categories based on the total score from the questionnaire above.
```{python eval=FALSE}
# Traditional Risk Profile 
def new_risk_profile():
    form = risk_profile()

    if form.validate_on_submit():
        q1 = form.q1.data
        q2 = form.q2.data
        q3 = form.q3.data
        q4 = form.q4.data
        q5 = form.q5.data
        q6= form.q6.data
        q7= form.q7.data
        q8 = form.q8.data
        q9 = form.q9.data
        q10 = form.q10.data

        answers = [int(q1), int(q2), int(q3), int(q4), int(q5), int(q6), int(q7), int(q8), int(q9), int(q10)]
        Sum = sum(answers)
        if Sum < 20:
            risk_profile = "Conservative"
        elif Sum >= 20 and Sum < 40:
            risk_profile = "Balanced"
        elif Sum >= 40 and Sum < 60:
            risk_profile = "Growth"
        elif Sum >= 60 and Sum <= 80:
            risk_profile = "Opportunistic"
        else:
            risk_profile = "All Equity"
        
        return render_template('results.html', risk_profile=risk_profile)
```

### Portfolio Recommendation
Finally, in this part, we naively present how the robo-advisor would recommend an investment strategy to the client based on the answers given to the questionnaire. We added two requirements: First, the client must be at least 18 years old and not yet retired to become a client with our company. Second, the minimum investment amount is CHF 5,000; a lower amount would simply not be interesting for us from an economic point of view. We have also added a small feature that allows the algorithm to automatically combine our recommended investment portfolio if the above two requirements are met.
```{python eval=FALSE}
# Final Recommendation
def portfolio_recommendation(intent_request):

    first_name = get_slots(intent_request)["firstName"]
    age = get_slots(intent_request)["age"]
    investment_amount = get_slots(intent_request)["investmentAmount"]

    if age is not None:
        age = parse_int(age)
            
        if age <18:
            return build_validation_result(False, "Your need to be at least 18 years old to use our service")
        elif age >=65:
            return build_validation_result(False, "You must not be retired yet")
       
    if investment_amount is not None:
        investment_amount = parse_int(investment_amount)
        if investment_amount < 5000:
            return build_validation_result(False,"The minimum investment amount is CHF 5'000")
        else:
            initial_recommendation = new_risk_profile
            return close(
    intent_request["sessionAttributes"],
        "Fulfilled",
    {
        "contentType": "PlainText",
        "content": """{} thank you for your information;
        Based on your answers, our recommendation is to choose the {} investment portfolio
        """.format(
            first_name, initial_recommendation
        ),
    },
)
    
```


### Rebalancing
In this small code section, we want to touch on another AI-driven process within Robo-Advisory: the rebalancing process. As the economy is constantly changing, so is the stock market and the respective stock prices. In order to keep the risk level constant (the risk level the client chose when they first invested), the robo-advisor (and any asset manager in general) must constantly adjust the allocation of each position within the investment portfolio to match the target allocation. This process can be done quite easily using AI. Starting from a predefined allocation overview of all components of the investment portfolio, the following pseudo-code can be used to regularly check (monthly or quarterly, depending on the client's preferences) whether the actual allocation in the portfolio still matches the target allocation. Deviations occur simply due to stock price increases/decreases. If discrepancies exist, either an additional purchase of the stock or a sale is ordered. Even though this process is not specifically affected by any recently introduced regulation (e.g. FIDLEG or FINIA), we still wanted to include a short pseudo code.
```{python eval=FALSE}
# Define target portfolio
target_portfolio = {
    "AAPL": 30.00,
    "IBM": 40.00,
    "AMZN": 25.00,
    "Cash": 5.00
}

# Define example portfolio which needs to be rebalanced
portfolio = {
    "AAPL": 40.00,
    "IBM": 35.00,
    "AMZN": 20.00,
    "CASH": 5.00
}

# Set tolerance value in %
tolerance = 5.00

# Iterate over all stocks in our current portfolio
total_value = 0
for i in portfolio:
    # Calculate the total value of our portfolio (including cash)
    if i == Cash:
        total_value += portfolio[i]
        continue
    total_value += price * portfolio[i]
    prices[i] = price

# Record which stocks need to be rebalanced
rebalance_needed = dict()
for i in target_portfolio:

    # Rebalance needed if: difference between example and target portfolio is greater than tolerance
    difference = ((prices[i] * portfolio[i]) / total_value) - target_portfolio[i]
      if abs(difference) > tolerance:
          rebalance_needed[i] = difference

# Now we can rebalance the portfolio
while rebalance_needed:
    quantity = int((target_portfolio[ticker] * (total_value / prices[ticker])) - portfolio[ticker])
```



