# Robo-Advisors
Consumers and investors are benefiting from both the emergence of new fintech solutions and the further development of existing financial service providers. This has led to a wider range of financial products and services being offered more efficiently and effectively, and companies are under competitive pressure to become more consumer-centric. However, the increasing use of fintech solutions and new technologies also entails risks to which regulators and supervisory authorities are reacting. In this chapter, we will first discuss and illustrate some AI-driven processes in the robo-advisory industry and illustrate the mechanism using pseudocodes to give the reader an understanding of how AI is driving this industry and, in some selected cases, also help develop a better understanding of which areas are affected by regulatory changes in practice. We then set out to analyze the impact of the regulations on startups, whether they are justified, whether they are really having the desired effect, and ultimately what impact they are having on the economy as a whole. To this end, we conducted several interviews with CEOs of fintech companies in Switzerland to obtain first-hand opinions from those most directly affected by the new regulations. Finally, we summarize these interviews in the last subchapter, which we will later refer to as "Voices from the Industry", where we ask Dr. Adriano Lucatelli, CEO and co-founder of Descartes Finance AG, Julian Liniger, CEO and co-founder of Relai AG, and Rino Borini, lecturer at HWZ and co-founder of Scarossa and House of Satosh, about their personal opinion of new regulations


## AI-driven process
A robo-advisor is a digital construct that typically relies on algorithms and/or AI to provide financial advice to clients. Below, we attempt to illustrate some of the AI-driven process of robo-advisors to exemplify how AI is used in practice. We have created several pseudocode's in the Python language to illustrate the exact mechanism by which the robo-advisor categorizes the client and then finally creates an investment advice. Note that we have only used a very naive questionnaire, which in reality would not comply with the revised FinSA, as we do not distinguish between risk capacity and risk preference as this would be needed to prevent any oversteering of the risk profile. One way to do this would be to count the risk capacity and risk preference scores separately and then use the respective lower score in each case for the final risk category assignment. At the end we also included a pseudocode for the rebalancing.

### Risk categories
In the following exemplary code we define 5 different risk categeories with the respective investment strategy name of which one later the robo-advisor wil assign the client to.
```{python eval=FALSE}
# Defining risk categories
def investment_recommendation():
    risk_levels = {
            'Conservative': '80% bonds, 20% equities',
            'Balanced': '60% bonds, 40% equities',
            'Growth': '40% bonds, 60% equities',
            'Opportunistic': '20% bonds, 80% equities',
            'All Equity': '0% bonds, 100% equities',
            
```


### Questionnaire and the respectivce scoring
What we are currently seeing in the robo-advisor industry is that questionnaires are generally being shortened to make it even more attractive for new clients to start investing. On the other hand, enough questions need to be asked to correctly identify the client's risk capacity and risk preference in order to comply with regulations such as the FIDLEG. For simplicity, we have included 10 questions in the following pseudocode.
```{python eval=FALSE}
# Questions
class risk_profile(FlaskForm):
    
    q1 = RadioField("1. Please enter your age", 
    choices = [
      ('0', 'More than 60'),
      ('2', 'Between 51 and 60'), 
      ('5', 'Between 41 and 50'), 
      ('8', 'Between 31 and 40'), 
      ('10', '30 or younger')])
    q2 = RadioField("2. What is your investment horizon?", choices = [
      ('0', 'Within the next year'), 
      ('2', '2 - 5 years'), 
      ('5', '5 - 10 years'), 
      ('8', '10 - 20 years'), 
      ('10', 'More than 20 years')])
    q3 = RadioField("3. If you were to lose your job, how long would you be able to finance your current living?", 
    choices = [
      ('0', '1 week'), 
      ('2', '1 month'), 
      ('5', '3 months'), 
      ('8', '6 months or more'), 
      ('10', 'I am already retired')])
    q4 = RadioField("4. What is your total annual income?", choices = [
      ('0', 'Less than CHF 50,000'), 
      ('2', 'CHF 50,000 - CHF 100,000'), 
      ('5', 'CHF 100,000 - CHF 150,000'), 
      ('8', 'CHF 150,000 - CHF 250,000'), 
      ('10', 'More than CHF 250,000')])
    q5 = RadioField("5. How is the stability of your income", 
    choices = [
      ('0', 'Low'), 
      ('2', 'Below average'), 
      ('5', 'Average'), 
      ('8', 'Above Average'), 
      ('10', 'Very Stable')])
    q6 = RadioField("6. If you would receive CHF 20,000 today, what would you do?", 
    choices = [
      ('0', 'Deposit it in bank account'), 
      ('2', 'Invest only in safe bonds'), 
      ('5', 'Invest in a mix of bonds and stocks'), 
      ('8', 'Invest only in stockss'), 
      ('10', 'Buy a new car')])
    q7 = RadioField("7. When you think of the word “risk” in a financial context, which of the following words come to mind?", 
    choices = [
      ('0', 'Loss'), 
      ('2', 'Dangerous'), 
      ('5', 'Uncertainty'), 
      ('8', 'Opportunity'), 
      ('10', 'Thrill')])
    q8 = RadioField("8. Which of the following statements would best describe your attitude regarding investing?", 
    choices = [
      ('0', "I need to see a little return"), 
      ('2', "I would have a hard time tolerating any losses"), 
      ('5', "I can tolerate a small loss"), 
      ('8', "I can tolerate a loss"), 
      ('10', "I don't mind a loss at all")])
    q9 = RadioField("9. Throughout the 2009 financial crisis, the SMI lost 50% of its value. Which of the following would you have done if your portfolio experiences a 50% loss?", 
    choices = [
      ('0', 'Sell all investments'), 
      ('2', "Move all investments into bonds"), 
      ('5', 'Change to a more conservative allocation'), 
      ('8', 'Hold on to investments'), 
      ('10', "Investeven  more")]) 
    q10 = RadioField("10. As return increases so does risk. Which statement applies to you?", 
    choices = [
      ('0', "I am not willing to accept any fluctuations in value"), 
      ('2', "I can live with fluctuations between 0% to 5%"), 
      ('5', "Value fluctuations between 5% and 10% are fine"), 
      ('8', "I can accept fluctuations between 10% and 20%"), 
      ('10', "Even fluctuations over 20% are fine for me")])
```

### Point distribution
Here, our pseudocode classifies the customer into one of five risk categories based on the total score from the questionnaire above.
```{python eval=FALSE}
# Traditional Risk Profile 
def new_risk_profile():
    form = risk_profile()

    if form.validate_on_submit():
        q1 = form.q1.data
        q2 = form.q2.data
        q3 = form.q3.data
        q4 = form.q4.data
        q5 = form.q5.data
        q6= form.q6.data
        q7= form.q7.data
        q8 = form.q8.data
        q9 = form.q9.data
        q10 = form.q10.data

        answers = [int(q1), int(q2), int(q3), int(q4), int(q5), int(q6), int(q7), int(q8), int(q9), int(q10)]
        Sum = sum(answers)
        if Sum < 20:
            risk_profile = "Conservative"
        elif Sum >= 20 and Sum < 40:
            risk_profile = "Balanced"
        elif Sum >= 40 and Sum < 60:
            risk_profile = "Growth"
        elif Sum >= 60 and Sum <= 80:
            risk_profile = "Opportunistic"
        else:
            risk_profile = "All Equity"
        
        return render_template('results.html', risk_profile=risk_profile)
```

### Portfolio Recommendation
Finally, in this part, we naively present how the robo-advisor would recommend an investment strategy to the client based on the answers given to the questionnaire. We added two requirements: First, the client must be at least 18 years old and not yet retired to become a client with our company. Second, the minimum investment amount is CHF 5,000; a lower amount would simply not be interesting for us from an economic point of view. We have also added a small feature that allows the algorithm to automatically combine our recommended investment portfolio if the above two requirements are met.
```{python eval=FALSE}
# Final Recommendation
def portfolio_recommendation(intent_request):

    first_name = get_slots(intent_request)["firstName"]
    age = get_slots(intent_request)["age"]
    investment_amount = get_slots(intent_request)["investmentAmount"]

    if age is not None:
        age = parse_int(age)
            
        if age <18:
            return build_validation_result(False, "Your need to be at least 18 years old to use our service")
        elif age >=65:
            return build_validation_result(False, "You must not be retired yet")
       
    if investment_amount is not None:
        investment_amount = parse_int(investment_amount)
        if investment_amount < 5000:
            return build_validation_result(False,"The minimum investment amount is CHF 5'000")
        else:
            initial_recommendation = new_risk_profile
            return close(
    intent_request["sessionAttributes"],
        "Fulfilled",
    {
        "contentType": "PlainText",
        "content": """{} thank you for your information;
        Based on your answers, our recommendation is to choose the {} investment portfolio
        """.format(
            first_name, initial_recommendation
        ),
    },
)
    
```


### Rebalancing
In this small code section, we want to touch on another AI-driven process within Robo-Advisory: the rebalancing process. As the economy is constantly changing, so is the stock market and the respective stock prices. In order to keep the risk level constant (the risk level the client chose when they first invested), the robo-advisor (and any asset manager in general) must constantly adjust the allocation of each position within the investment portfolio to match the target allocation. This process can be done quite easily using AI. Starting from a predefined allocation overview of all components of the investment portfolio, the following pseudo-code can be used to regularly check (monthly or quarterly, depending on the client's preferences) whether the actual allocation in the portfolio still matches the target allocation. Deviations occur simply due to stock price increases/decreases. If discrepancies exist, either an additional purchase of the stock or a sale is ordered. Even though this process is not specifically affected by any recently introduced regulation (e.g. FIDLEG or FINIA), we still wanted to include a short pseudo code.
```{python eval=FALSE}
# Define target portfolio
target_portfolio = {
    "AAPL": 30.00,
    "IBM": 40.00,
    "AMZN": 25.00,
    "Cash": 5.00
}

# Define example portfolio which needs to be rebalanced
portfolio = {
    "AAPL": 40.00,
    "IBM": 35.00,
    "AMZN": 20.00,
    "CASH": 5.00
}

# Set tolerance value in %
tolerance = 5.00

# Iterate over all stocks in our current portfolio
total_value = 0
for i in portfolio:
    # Calculate the total value of our portfolio (including cash)
    if i == Cash:
        total_value += portfolio[i]
        continue
    total_value += price * portfolio[i]
    prices[i] = price

# Record which stocks need to be rebalanced
rebalance_needed = dict()
for i in target_portfolio:

    # Rebalance needed if: difference between example and target portfolio is greater than tolerance
    difference = ((prices[i] * portfolio[i]) / total_value) - target_portfolio[i]
      if abs(difference) > tolerance:
          rebalance_needed[i] = difference

# Now we can rebalance the portfolio
while rebalance_needed:
    quantity = int((target_portfolio[ticker] * (total_value / prices[ticker])) - portfolio[ticker])
```

## FinSA
The FinSa primarily regulates how financial services must be provided and how financial instruments must be offered. In the following, some articles from the FinSA, which are assumed to have triggered the greatest changes for startups, are singled out and analyzed in detail.


## FADP


## Voices from the industry
In this subsection, we want to let people from the industry have their say about what they think about regulation, how new laws affect their business, and what they would like to see changed.

### WealthTech
*Digital-only asset manager Descartes Finance AG, one of the leading Swiss FinTech startups in the area of Robo-Advisory, aims to democratize investing, both in asset management and pensions. Likewise, the WealthTech startup is focused on sustainability, both internally and externally using ESG-compliant investment products. We had the opportunity to sit down with CEO and co-founder Dr. Adriano Lucatelli and ask him questions regarding the recently introduced FinSa and his overall opinion on regulations in the financial sector. The full interview as video can be watched [here (ADD YOUTUBE LINK !!!!)](https://www.youtube.com)*

> "Regulation should primarily try to prevent macroeconomic financial shocks, not regulate every single process in the financial industry."
>
> -- Dr. Adriano Lucatelli

In Switzerland, WealthTechs are in principle subject to the same regulations as traditional financial institutions. These regulations are extensive, creating significant barriers to entry for WealthTechs. However, many of the WealthTechs in Switzerland are based on artificial intelligence (as is Descartes Finance AG), which in theory eliminates human bias in wealth management and allows wealth managers to focus on relationship building. While these tighter regulations may be necessary for traditional wealth management, for WealthTech’s they do not improve processes or client protection, and instead simply increase the cost of doing business. In practice, WealthTech’s, which were supposed to revolutionize wealth management, compete with large financial institutions like UBS and Credit Suisse. 
As an example, the newly introduced FinSa did not contribute significantly to customer protection, but only increased the cost of compliance for the startup, which in turn consumed money that could have been used elsewhere to innovate the services and products offered, so Lucatelli. Ultimately, all these new regulations won't do much but rather hinder innovation, Lucatelli says.
He also uses the crypto market as an example to show what regulations ultimately do to innovation: While asset management, as part of the banking sector, has been heavily regulated since its early days, we have seen the emergence of the new crypto market where there were initially no regulations at all. At the same time, we also saw all the young startups in crypto bursting with innovation and growing into legitimate businesses with ease and within a short period of time. In addition, Lucatelli points out that industry-specific regulations in the financial sector are not helpful. He would prefer to see less regulation overall so that customers have to take more responsibility for their own actions

### Crypto Industry

*In contrast to Descartes Finance AG, which is active in the wealth management industry, Relai AG is operating in the area of cryptocurrencies. We have already talked about why Switzerland in particular is a favourable location for cryptocurrency and blockchain businesses. A number of different factors have certainly contributed to Switzerland coming out on top. One of them is an efficient and transparent government. Another advantage was the lack of registration requirements for ICOs and blockchain-related businesses and crypto companies. Likewise, very few regulations and laws relevant to crypto companies exist even today. It seems like both the Swiss government and the Financial Market Supervisory Authority (FINMA) might have recognized the potential of cryptocurrencies. For regulatory purposes, FINMA has imposed anti-money laundering (AML) and know-your-customer (KYC) requirements in Switzerland. In addition, new transaction thresholds for KYC checks were introduced this month, lowering threshold value for exchange transactions in cryptocurrencies from CHF 5’000 to CHF 1’000.*

#### Relai AG: “Europe’s easiest Bitcoin investment app”
In the case of Relai AG, the startup is not directly regulated by FINMA, but indirectly via a self-regulatory organization (SRO). This is because the Anti-Money Laundering Act (AML) stipulates that financial intermediaries must join an SRO organized under private law to monitor compliance with due diligence requirements to prevent and avoid money laundering. One major advantage for Relai’s clients is that they can use the app and invest in Bitcoin without registration or verification if the daily investment amount does not exceed CHF 1,000 and/or the annual investment amount does not exceed CHF 100,000. This is the key to Relai’s attractiveness and success, as most of its younger clientele can start investing within a few minutes. However, a slowly growing portion of Relai's customers exceed the above investment amounts which then requires a registration. The startup was therefore indirectly forced to acquire a broker license in order to circumvent the recently introduced changes regarding the lowering of the threshold for cryptocurrency exchanges and thus maintain its attractiveness for its clients.

Liniger also explicitly emphasized in our interview that the fact that Switzerland has such lax regulation regarding cryptocurrencies made it possible to found their startup in the first place. According to Liniger, the regulatory situation in Switzerland is unique compared to other European countries. This might be an indication that regulation is indeed an important factor for the innovative power of the startup scene. In particular, if we compare the two industries of asset management and cryptocurrencies, in the latter we can see that more and more fintechs are emerging. Liniger also goes on to say that he personally appreciates the fact that in Switzerland, new regulations are not introduced from one day to the next, but rather take a long time, so that the industry has enough time to adjust. He would even go so far as to say that this is an advantage that Switzerland has compared to other European countries. He also mentions that he thinks Switzerland is very innovation friendly and he really appreciates the sandbox environment. Also, most fintechs in the crypto industry do not need a full banking license, but FINMA offers "light versions". 

#### House of Satoshi: “Home of Bitcoin”
*Rino Borini is co-founder and CEO of Scarossa, an independent consulting and media company, and the House of Satoshi, a store for crypto currencies located in Zurich where you can, among other things, convert crypto currencies into currencies. In the fall of 2020, the business magazine BILANZ named Borini one of the Digital Shapers, i.e. the 100 most important minds driving digitalization in the country. Rino Borini is also chairman of the board of directors at digital asset manager Descartes Finance. Moreover, he is also the course director for the "Digital Finance" and "Digital Insurance" courses at HWZ Zurich.*

He starts our interview by asserting that he sees no difference between traditional banks and fintech startups when it comes to regulation in Switzerland. He thinks that with fintech licensing and sandboxes, an environment has been created that could actually foster innovation. But when he hears from startups how long it takes to get a license, which is the basic requirement for a startup to get started, he gets extremely frustrated. He strongly believes that the licensing process needs to be massively accelerated on the one hand, and also simplified on the other.

Borini further explains that he likes the regulations in the crypto industry as, compared internationally, Switzerland has one of the most modern DLT laws. So Switzerland does have the opportunity to develop exciting technologies in the crypto economy. But then, at the same time, he also sees circumstances that clearly hinder innovation in Switzerland: On the one hand, FINMA, which seems to violate technology neutrality, as FINMA does not necessarily regulate crypto and fintech identically, and on the other hand, traditional banks, which do not want to help crypto startups. To back up his criticism towards technology neutrality, he mentions the example of the CHF 1,000 limit for cryptocurrencies, "If I go to the traditional ATM, I can withdraw CHF 5,000 per day, but with crypto ATMs I now have a limit of CHF 1,000. So fiat money is treated differently than cryptocurrency," Borini says. This ultimately leads to innovation dampening on the one hand and also does not fit with the slogan "Blockchain Nation Switzerland." Further, he adds that it is extremely difficult for crypto startups to find a partner bank. Even just opening an account can be very difficult. “Not because it's not legally possible, but because banks simply don't want it”, according to Borini. He also hopes that FINMA will set a framework for DeFi (Decentralized Finance) as soon as possible. Otherwise, Switzerland should soon stop calling itself "Blockchain Nation Switzerland”. 

Regarding the question of what Switzerland should do in terms of regulations to promote innovation, Borino answers that with wealth tech and crypto, Switzerland has great potential to maintain a leading role internationally. In particular, he wishes Swiss citizens had more knowledge about the technologies and the potentials associated with them. According to Borino, we should have a different mindset: Not "yes, but..." but "yes, why not?" Regulators should also work much more closely with industries. Similarly, regulations should be updated much more often and adapted to circumstances. Borino believes that FINMA should not innovate the industry itself, but simply allow it. And likewise, FINMA needs a power team with leaders from the industry and the community who understand the technology and potential and actively listen to startups to identify problems. And finally, according to Borini, there should be a "fast lane," like at the airport, for the startups that have everything ready to go, so to speak, and could get going, have a good business model, and comply with laws and regulations. This way, these startups can quickly get a license and start doing business. 
