# AI in FinTech: A Robo-Advisory Case Study

## Robo-Advisory Regulation: Recent Developments



## AI-driven Processes
Robo-advisors differ by institution, based on their underlying algorithm. However, their implementation steps are consistently the same. Clients first complete a questionnaire to assess risk tolerance, investment ambition and needs. Based on this information, the robo-advisor builds a diversified portfolio based on an algorithm, a set of predefined rules, created by investment professionals. These investment professionals monitor market signals and ensure that the algorithm is rebalancing the portfolio appropriately^[“Robo-Advisors: An Introduction”, accessed 4 May 2022, https://www.schwab.com/automated-investing/what-is-a-robo-advisor]. 

We have created pseudocode chunks in Python to illustrate the mechanism by which the robo-advisor categorizes the client, assigns a portfolio and rebalances it. Note that we have only used a very naive questionnaire, which in reality would not comply with the revised FinSA, as we do not distinguish between risk capacity and risk preference. This step would be needed to prevent any risk oversteering. In practice, this may be done by using the lowest score between risk capacity and preference for the final risk category assignment. The AI-portfolio attribution process has been highly simplified, with investment strategies consisting of simple bond to equity ratios. 


### Risk categories
First, 5 risk categories are defined. Each one corresponds to an investment strategy that the client will be assigned to by the robo-advisor. 
```{python eval=FALSE}
# Defining risk categories
def investment_recommendation():
    risk_levels = {
            'Conservative': '80% bonds, 20% equities',
            'Balanced': '60% bonds, 40% equities',
            'Growth': '40% bonds, 60% equities',
            'Opportunistic': '20% bonds, 80% equities',
            'All Equity': '0% bonds, 100% equities',      
    }   
```

### Questionnaire
Current trends in the robo-advisory industry show questionnaires are generally being shortened to make robo-advisory solutions more attractive to new clients. However, enough questions need to be asked to correctly identify the client’s risk capacity and risk preference and to comply with regulations such as the FinSA. For simplicity, we have included 10 questions in the following pseudocode, which are inspired by several leading Swiss robo-advisors^[We looked at the questionnaire of, among others, Descartes Finance AG, True Wealth and Inyova].

```{python eval=FALSE}
# Questions
class risk_profile:
    
    q1 = ("1. Please enter your age", 
    choices = [
      ('0', 'More than 60'),
      ('2', 'Between 51 and 60'), 
      ('5', 'Between 41 and 50'), 
      ('8', 'Between 31 and 40'), 
      ('10', '30 or younger')])
    q2 = ("2. What is your investment horizon?", choices = [
      ('0', 'Within the next year'), 
      ('2', '2 - 5 years'), 
      ('5', '5 - 10 years'), 
      ('8', '10 - 20 years'), 
      ('10', 'More than 20 years')])
    q3 = ("3. If you were to lose your job, how long would you be able to finance your current living?", 
    choices = [
      ('0', '1 week'), 
      ('2', '1 month'), 
      ('5', '3 months'), 
      ('8', '6 months or more'), 
      ('10', 'I am already retired')])
    q4 = ("4. What is your total annual income?", choices = [
      ('0', 'Less than CHF 50,000'), 
      ('2', 'CHF 50,000 - CHF 100,000'), 
      ('5', 'CHF 100,000 - CHF 150,000'), 
      ('8', 'CHF 150,000 - CHF 250,000'), 
      ('10', 'More than CHF 250,000')])
    q5 = ("5. How is the stability of your income", 
    choices = [
      ('0', 'Low'), 
      ('2', 'Below average'), 
      ('5', 'Average'), 
      ('8', 'Above Average'), 
      ('10', 'Very Stable')])
    q6 = ("6. If you would receive CHF 20,000 today, what would you do?", 
    choices = [
      ('0', 'Deposit it in bank account'), 
      ('2', 'Invest only in safe bonds'), 
      ('5', 'Invest in a mix of bonds and stocks'), 
      ('8', 'Invest only in stockss'), 
      ('10', 'Buy a new car')])
    q7 = ("7. When you think of the word “risk” in a financial context, which of the following words come to mind?", 
    choices = [
      ('0', 'Loss'), 
      ('2', 'Dangerous'), 
      ('5', 'Uncertainty'), 
      ('8', 'Opportunity'), 
      ('10', 'Thrill')])
    q8 = ("8. Which of the following statements would best describe your attitude regarding investing?", 
    choices = [
      ('0', "I need to see a little return"), 
      ('2', "I would have a hard time tolerating any losses"), 
      ('5', "I can tolerate a small loss"), 
      ('8', "I can tolerate a loss"), 
      ('10', "I don't mind a loss at all")])
    q9 = ("9. Throughout the 2009 financial crisis, the SMI lost 50% of its value. Which of the following would you have done if your portfolio experiences a 50% loss?", 
    choices = [
      ('0', 'Sell all investments'), 
      ('2', "Move all investments into bonds"), 
      ('5', 'Change to a more conservative allocation'), 
      ('8', 'Hold on to investments'), 
      ('10', "Investeven  more")]) 
    q10 = ("10. As return increases so does risk. Which statement applies to you?", 
    choices = [
      ('0', "I am not willing to accept any fluctuations in value"), 
      ('2', "I can live with fluctuations between 0% to 5%"), 
      ('5', "Value fluctuations between 5% and 10% are fine"), 
      ('8', "I can accept fluctuations between 10% and 20%"), 
      ('10', "Even fluctuations over 20% are fine for me")])
```

### Point distribution
After collecting the relevant client information and attributing a score, the robo-advisor classifies the customer into one of five risk categories. 
```{python eval=FALSE}
# Traditional Risk Profile 
def new_risk_profile():
    form = risk_profile()

    if Sum < 20:
        risk_profile = "Conservative"
    elif Sum >= 20 and Sum < 40:
        risk_profile = "Balanced"
    elif Sum >= 40 and Sum < 60:
        risk_profile = "Growth"
    elif Sum >= 60 and Sum <= 80:
        risk_profile = "Opportunistic"
    else:
        risk_profile = "All Equity"
        
    return result
```

### Portfolio Recommendation
Finally, in this part, we naively present how the robo-advisor would recommend an investment strategy to the client based on the answers given to the questionnaire. We added two requirements: First, the client must be at least 18 years old and not yet retired to become a client with our company. Second, the minimum investment amount is CHF 5,000; a lower amount would simply not be interesting for us from an economic point of view. One should note that these investment strategies are, in practice, the fruit of careful optimization algorithms based on (in the case of Switzerland) SMI stocks and bonds and/or ETFs. 
```{python eval=FALSE}
# Final Recommendation
def portfolio_recommendation():

    first_name = ["First_Name"]
    age = ["Age"]
    investment_amount = ["Investment_Amount"]

    if age < 18:
        return build_validation_result("You need to be at least 18 years old to use our service")
    elif age >= 65:
        return build_validation_result("You must not be retired yet")
       
    if investment_amount < 5000:
        return build_validation_result("The minimum investment amount is CHF 5'000")
    
```


### Rebalancing
In this small code section, we want to touch on another AI-driven process within Robo-Advisory: the rebalancing process. As the economy is constantly changing, so is the stock market and the respective stock prices. In order to keep the risk level constant (the risk level the client chose when they first invested), the robo-advisor (and any asset manager in general) must constantly adjust the allocation of each position within the investment portfolio to match the target allocation. This process can be done quite easily using AI. Starting from a predefined allocation overview of all components of the investment portfolio, the following pseudo-code^[This pseudo-code is inspired by Github user **siavashadpey**, accessible through following link: https://github.com/siavashadpey/rebalance] can be used to regularly check (monthly or quarterly, depending on the client's preferences) whether the actual allocation in the portfolio still matches the target allocation. Deviations occur simply due to stock price increases/decreases. If discrepancies exist, either an additional purchase of the stock or a sale is ordered. Even though this process is not specifically affected by any recently introduced regulation (e.g. FIDLEG or FINIA), we still wanted to include a short pseudo code.
```{python eval=FALSE}
# Define target portfolio
target_portfolio = {
    "AAPL": 30.00,
    "IBM": 40.00,
    "AMZN": 25.00,
    "Cash": 5.00
}

# Define example portfolio which needs to be rebalanced
portfolio = {
    "AAPL": 40.00,
    "IBM": 35.00,
    "AMZN": 20.00,
    "CASH": 5.00
}

# Set tolerance value in %
tolerance = 5.00

# Iterate over all stocks in our current portfolio
for i in portfolio:
    # Calculate the total value of our portfolio (including cash)
    if i == Cash:
        total_value += portfolio[i]
        continue
    total_value += price * portfolio[i]

# Record which stocks need to be rebalanced
rebalance_needed = dict()
for i in target_portfolio:

    # Rebalance needed if: difference between example and target portfolio is greater than tolerance
    difference = ((prices[i] * portfolio[i]) / total_value) - target_portfolio[i]
      if (difference) > tolerance:
          rebalance_needed[i] = difference

# Now we can rebalance the portfolio
while rebalance_needed:
    quantity = int((target_portfolio[ticker] * (total_value / prices[ticker])) - portfolio[ticker])
```



