# DLT-Based FinTechs: Market and Regulation

Switzerland’s success story as a FinTech hub depends in large part on DLT-based FinTechs, indeed 11 of its unicorns are companies operating in the blockchain technology segment^[“Swiss Crypto-Valley boasts 14 ‘unicorns’”, accessed 4 May 2022, https://www.swissinfo.ch/eng/swiss--crypto-valley--boasts-14--unicorns-/47291870.]. DLT is the second largest technology segment in the FinTech market in Switzerland, according to the 2022 IFZ FinTech Study^[@Ankenbrand2022, p. 7.]. The study enumerates 113 DLT-based companies in 2021. However, companies falling into the DLT area are those which, for example, “offer payment systems for cryptocurrencies or loan platforms in the area of Decentralized Finance (DeFi)”, and only 63 DLT-backed companies with headquarters in Zug are included in this study. These numbers pale in comparison to the total 960 Crypto-Valley companies operating in Switzerland, including 433 based in Zug^[“Crypto Valley home to even more Unicorns”, accessed 4 May 2022, https://www.s-ge.com/en/article/news/20211-blockchain-crypto-valley-unicorns.]. In fact, crypto/crypto-assets and related blockchain companies are a unique segment of FinTech that doesn’t always enter the study’s scope.

This chapter tells the story of blockchain-based FinTechs in Switzerland, and details its unique regulation to serve as a contrast to that of other FinTechs in Switzerland, and A.I.-based WealthTechs in particular.

## The Crypto-Valley Success Story 

The development of what is today known as Crypto Valley all began with advantageous corporate tax rates. In 2012, 1 in 16 new Swiss companies registered in Zug, with the main appeal being its corporate tax rate^[“Life in a nice, clean swiss tax haven”, accessed 4 May 2022, https://www.swissinfo.ch/eng/taxing-matters_life-in-a-nice--clean-swiss-tax-haven/32846350.], then about half the national average. At that time,^[“Life in a nice, clean swiss tax haven”, accessed 4 May 2022, https://www.swissinfo.ch/eng/taxing-matters_life-in-a-nice--clean-swiss-tax-haven/32846350.]  the tax levy on corporate profit is 15% for ordinary, and 8.8% for privileged companies. Almost all of the levied tax went to the federal government since cantonal and communal rates in Zug were -and remain- close to 0%. Beyond corporate tax rates at the time, individual taxes were around 23% in Zug, compared to 40% in France, Germany and Italy and 50% in Britain, Austria and the Netherlands.

In 2013, the Crypto Valley earns its name when digital notary Bitcoin (BTC) Suisse and Monetas^[“Zug: From Silicon Valley to Crypto Valley”, accessed 4 May 2022, https://www.juliusbaer.com/es/insights/digitalizacion/zug-from-silicon-valley-to-crypto-valley/.] move their operations to Zug for tax purposes and favourable ICO laws^[“Zug: From Silicon Valley to Crypto Valley”, accessed 4 May 2022, https://www.juliusbaer.com/es/insights/digitalizacion/zug-from-silicon-valley-to-crypto-valley/.] . The notoriety of the area became international when then 23-year-old Vitalik Buterin moved the Ethereum Foundation to Zug (worth today CHF 157.2 billion ^[“Crypto Valley home to ever more unicorns”, accessed 4 May 2022, https://www.s-ge.com/en/article/news/20211-blockchain-crypto-valley-unicorns.], the most valuable company in crypto-space in Switzerland) and triggered an overnight influx of start-ups operating in the same space. According to the Top 50 VC CV report^[“CV VC Global Report”, accessed 4 May 2022, https://www.cvvc.com/insights.], the figures we see in Switzerland make it the “most mature blockchain hub” in the world. The attractiveness of the valley goes beyond favourable tax rates and also includes a favourable regulatory framework and pro-activity from the government. For example, Zug was the first city in the world to accept payments in BTC, and FINMA granted full banking licenses to two crypto-banks, Seba and Sygnum^[“Switzerland’s Cryptovalley looks past cold market winds”, accessed 4 May 2022,  https://www.ft.com/content/b827f5c4-1278-4e36-8c5e-e450a325c16f.]. 

## The Blockchain Act

> "With the newly introduced Blockchain legislation, Switzerland boasts one of the world's most advanced Blockchain legislations and has thus created a strong and solid foundation for the future prosperity of Crypto Valley.”
>
> -- Ralf Kubli, CV VC Top 50 Report Author

> “In five or ten years’ time I don’t want people to be talking about Crypto Valley Zug. I want people to be talking about Crypto Nation Switzerland.” 
>
> -- Swiss Economics Minister Johann Schneider-Ammann, January 2018

> “As of next year, Switzerland will have a regulatory framework that is among the most advanced in the world”
>
> -- Heinz Tännler, President of the Swiss Blockchain Federation 

On September 25th 2020, the Parliament passed the Federal Act on the Adaptation of Federal Law to Developments in Distributed Electronic Register Technology (DLTA)^[“Blockchain / DLT”, accessed 4 May 2022, https://www.sif.admin.ch/sif/en/home/finanzmarktpolitik/digitalisation-financial-sector/blockchain.html.], commonly known as the “Blockchain Act”. The Act is a legislative package impacting different federal-level laws^[Exhaustively: Financial Services Act (FinSA), the National Bank Act (NBA), the Banking Act (BA), the Financial Institutions Act (FinIA), the Anti-Money Laundering Act (AMLA), the Financial Market Infrastructure Act (FMIA), and the Debt Enforcement and Bankruptcy Act (DEBA).] ranging from securities trading to bankruptcy and was welcomed with open arms by the DLT industry. The blanket ordinance mandates the legal adjustments in ten ordinances with the aim of “[improving] the conditions for blockchain and DLT companies in Switzerland, thereby making the country an international pioneer in modern regulation of innovative financial market technologies”^[“Federal Council bring DLT Act fully into force and issues new ordinance”, accessed 4 May 2022, https://www.admin.ch/gov/en/start/documentation/media-releases/media-releases-federal-council.msg-id-84035.html.]. A first portion of the adopted amendments came into force on February 1st 2021 (amendments to the Swiss Code of Obligations), and a second on August 1st 2021. 

In particular, the new laws address the segregation of digital assets in case of bankruptcy, and access to data and personal information^[“Swiss DLT-law: New regulations ring new opportunities.”, accessed 3 May 2022, https://www.pwc.ch/en/insights/regulation/swiss-dlt-new-regulations.html#:~:text=In%20September%202020%2C%20the%20Swiss,act%20adapts%20various%20federal%20laws.]. These new rules become one of “the most advanced in the world” according to Heinz Tännler, by providing clarity in otherwise legally vague situations, which effectively increases the security of clients. Further, DLT securities have now entered the Swiss Code of Obligations^[Federal Act on the Amendment of the Swiss Civil Code (Part Five: The Code of Obligations) of July 1st, 1911 (“CO”; CC 220).] as “registered uncertified securities”. These securities no longer require a signed cession for their transfer to be legal, and do not require a central securities depository. These measures should significantly improve companies’ “ability (...) to issue instruments representing equity or debt, significantly reducing the cost and effort of raising capital.  They are also expected to improve liquidity by making the transfer and secondary trading of DLT Securities easier and more directly and broadly accessible”^[“Swiss DLT-law: New regulations ring new opportunities.”, accessed 3 May 2022, https://www.pwc.ch/en/insights/regulation/swiss-dlt-new-regulations.html#:~:text=In%20September%202020%2C%20the%20Swiss,act%20adapts%20various%20federal%20laws.].






