# FinTech Regulation in the U.K.

This chapter draws comparisons between the legislation and market conditions in Switzerland and those in the United Kingdom. Indeed, the United Kingdom shares a similar banking history with Switzerland and occupies the 7th place in IFZ’s FinTech hub ranking in 2022[@Ankenbrand2022]. The comparison is further motivated by the fact Switzerland and the United Kingdom are the largest financial centers in Europe and share a forward-looking vision of the world in terms of innovation^[‘Relationship building: the significant role of Switzerland and the UK in the financial sector’, accessed May 2022
,https://www.lombardodier.com/contents/corporate-news/corporate/2021/april/relationship-building-the-signif.html.]. We go into detail about the United Kingdom’s FinTech market, its legislative landscape and its corporate tax and sandbox regimes. 

## FinTechs in the United Kingdom

Over the last decade, the United Kingdom and London in particular have become a global FinTech hub, with 18% of worldwide funding for FinTechs raised on its soil. This number is topped only by the United States, with 47% of global FinTech funding raised[@Cornelli2020]. As did Switzerland (1.1.1), the United Kingdom had a record year in annual FinTech investment in 2021, exceeding USD 11.6b, representing a huge 217% increase from the previous year^[‘UK sees record year for FinTech investment – reaching $11.6bn in 2021’, accessed May 2022,
https://www.innovatefinance.com/news/uk-sees-record-year-for-FinTech-investment-reaching-11-6bn-in-2021-2/.]. 

The United Kingdom has a particularly strong WealthTech and payments technology industry, together accounting for more than 50% of the market. While London is the hub of the industry within the kingdom, wealtech is particularly active in the city, with 77% of this business segment being based there. A second WealthTech cluster can also be found in Scotland^[‘The UK FinTech Landscape
‘, accessed May 2022, https://www2.deloitte.com/uk/en/pages/financial-services/articles/uk-FinTech-landscape.html.]. 

## Regulatory Landscape

The United Kingdom government has articulated its goal to make the United Kingdom the world capital of FinTechs. Thus, it is really supportive of innovation and development of FinTechs in the territory^[@Donovan2021 , p. 317.]. 

As in Switzerland, in the United Kingdom there is no specific regulatory framework for FinTech companies. Thus, they are subject to the existing body of United Kingdom financial regulation. It will therefore be necessary to look at each law to see if it is likely to apply to the FinTech business. Therefore, the question of whether a particular activity is regulated can be complex ^[@Donovan2021 , p. 316.]. 

If a FinTech wishes to undertake activities that are regulated then it will need to obtain authorisation from the Financial Conduct Authority (FCA) or the Prudential Regulation Authority (PRA) which provide regulatory oversight of financial services in the UK^[“FCA vs PRA”, accessed 4 May 2022, https://control-now.com/faq/fca-vs-pra/.]. After the FinTech has obtained authorization from the authority, additional primary legislation will apply, as well as detailed regulations issued by the FCA and PRA^[@Donovan2021 , p. 316.].

Corporate Taxation
The corporate taxation rates in the United Kingdom are defined during the Budget sessions. Under the current budget, the normal taxation rate of 19% will remain in force until the end of the fiscal year 2022^[“United Kingdom, Corporate - Taxes on corporate income”, accessed 4 May 2022, https://taxsummaries.pwc.com/united-kingdom/corporate/taxes-on-corporate-income.]. There are no special tax regimes depending on size or profits. If taxable profits are attributable to patents, however, a tax rate of 10% applies. This may indeed be the case for WealthTechs with patented algorithms. The banking industry also sees a particular exception of an 8% supplementary tax on profits exceeding GBP 25 million ^[“United Kingdom, Corporate - Taxes on corporate income”, accessed 4 May 2022, https://taxsummaries.pwc.com/united-kingdom/corporate/taxes-on-corporate-income.]. 

According to Spring Budget 2021^[“Rates and allowances for Corporations”, accessed 4 May 2022, https://www.gov.uk/government/publications/rates-and-allowances-corporation-tax/rates-and-allowances-corporation-tax#:~:text=At%20Budget%202020%2C%20the%20government,2021%20would%20remain%20at%2019%25.],  for businesses with profits exceeding GBP 250’000 the main taxation rate will rise from 19% to 25% with effect from April 1st 2023. 19% will remain applicable for businesses with revenues thereunder and businesses with profits below GBP 50’000 will benefit from small profits rates. 

Start-ups and tech companies, can also benefit from certain tax relief schemes^[“Understanding Tax: The United Kingdom tax opportunities for corporate and FinTech startups”, accessed 4 May 2022, https://www.whitecase.com/publications/alert/understanding-tax-uk-tax-opportunities-corporate-and-FinTech-startups.]: 

* Entrepreneur’s relief: a possible reduction in capital gains tax from 20% to 10% on the sale of the entrepreneur’s business on up to GBP 1 million of gains

* Enterprise Management Incentive: companies may offer share options to make the companies’ tax term more efficient and boost productivity of the enterprise

* Enterprise investment schemes: offering tax relief up to 30% of value of their investment to investors of riskier trading companies

* Research and Development (R&D) regime: significant innovation in science and tech is rewarded with deductions in profits to lower taxable basis

* Patent box regime: aforementioned 10% tax rate on profits attributable to patents

## Sandbox Regime

The regulatory sandbox in the United Kingdom is one of the important channels making it a FinTech hub. The regime was first introduced by the United Kingdom’s FCA in November 2015[@Fahy2022] and was subsequently introduced in about 60 countries^[“Four years and counting: What we've learned from regulatory sandboxes”, accessed 4 May 2022,  https://blogs.worldbank.org/psd/four-years-and-counting-what-weve-learned-regulatory-sandboxes.].

While WealthTechs have been the dominant business segment in the industry, the United Kingdom is trying to become a cryptocurrency hub by making Stablecoins a recognized and valid payment method. By 2023, the United Kingdom will develop a Finance Market Structure (FMI) Sandbox to support firms wanting to innovate, especially targeting DLT technology. Under this new FMI sandbox, participants can request exemptions from or modifications to existing legislation to facilitate testing of DLT in FMIs and enable the United Kingdom authorities to gain a better understanding of the legislative changes necessary to accommodate DLT^[“UK Treasury Moves Forward with Plans to Regulate Stablecoins for Payments”, accessed May 2022,
 https://www.jdsupra.com/legalnews/uk-treasury-moves-forward-with-plans-to-5250715/.].
 
From August 2021, the United Kingdom’s regulatory sandbox moved to an always-open model, allowing firms to submit their applications throughout the year. Firms can now access FCA’s testing services at any point throughout the year, at the right point in their development lifecycle, at a time that works the best for them^[“Regulatory Sandbox”, accessed May 2022, https://www.fca.org.uk/firms/innovation/regulatory-sandbox.].

According to the FCA, the eligibility criteria for the United Kingdom’s regulatory sandbox test are following^[“Regulatory Sandbox Eligibility Criteria”, accessed May 2022, https://www.fca.org.uk/firms/innovation/regulatory-sandbox/eligibility-criteria.]:

* In scope: whether the customer base is located in the United Kingdom
* Genuine Innovation: whether the business proposal exhibits genuine difference
* Consumer benefit: whether the business benefits the consumer
* Readiness: whether the innovation is mature enough to be tested on the market
* Need for support: whether the sandbox regime is genuinely needed 

Sandboxes have been very effective in the United Kingdom. Empirical evidence from @Cornelli2020 shows that firms entering the sandbox between 2014 and 2019 see an increase of 15% in capital raised post-entry; their probability of raising capital increases by 50%. By reducing asymmetric information and regulatory costs, the sandbox facilitates access to capital [@Cornelli2020, p.26]. 

