# Voices from the Industry
In this section, we relay some of the main lessons learned when interviewing actors of the Zurich FinTech scene. Each one of their full interviews is available through a hyperlink. 

## Descartes Finance AG
*Dr. Adriano Lucatelli is the CEO and Co-Founder of the digital-only asset management firm Descartes Finance AG, a leading Robo-advisory firm in Switzerland. This firm belongs to the business area of Investment Management and is A.I.-based. View the full interview here.*

> "Regulation should primarily try to prevent macroeconomic financial shocks, not regulate every single process in the financial industry."
>
> -- Dr. Adriano Lucatelli

In Switzerland, WealthTechs are in principle subject to the same regulations as traditional financial institutions. These regulations are extensive, creating significant barriers to entry for WealthTechs. However, many of the WealthTechs in Switzerland are based on artificial intelligence (as is Descartes Finance AG), which in theory eliminates human bias in wealth management and allows wealth managers to focus on relationship building. While these tighter regulations may be necessary for traditional wealth management, for WealthTech’s they do not improve processes or client protection, and instead simply increase the cost of doing business. In practice, WealthTech’s, which were supposed to revolutionize wealth management, compete with large financial institutions like UBS and Credit Suisse. 
As an example, the newly introduced FinSa did not contribute significantly to customer protection, but only increased the cost of compliance for the startup, which in turn consumed money that could have been used elsewhere to innovate the services and products offered, so Lucatelli. Ultimately, all these new regulations won't do much but rather hinder innovation, Lucatelli says.
He also uses the crypto market as an example to show what regulations ultimately do to innovation: While asset management, as part of the banking sector, has been heavily regulated since its early days, we have seen the emergence of the new crypto market where there were initially no regulations at all. At the same time, we also saw all the young startups in crypto bursting with innovation and growing into legitimate businesses with ease and within a short period of time. In addition, Lucatelli points out that industry-specific regulations in the financial sector are not helpful. He would prefer to see less regulation overall so that customers have to take more responsibility for their own actions

## Crypto Industry

*In contrast to Descartes Finance AG, which is active in the wealth management industry, Relai AG is operating in the area of cryptocurrencies. We have already talked about why Switzerland in particular is a favourable location for cryptocurrency and blockchain businesses. A number of different factors have certainly contributed to Switzerland coming out on top. One of them is an efficient and transparent government. Another advantage was the lack of registration requirements for ICOs and blockchain-related businesses and crypto companies. Likewise, very few regulations and laws relevant to crypto companies exist even today. It seems like both the Swiss government and the Financial Market Supervisory Authority (FINMA) might have recognized the potential of cryptocurrencies. For regulatory purposes, FINMA has imposed anti-money laundering (AML) and know-your-customer (KYC) requirements in Switzerland. In addition, new transaction thresholds for KYC checks were introduced this month, lowering threshold value for exchange transactions in cryptocurrencies from CHF 5’000 to CHF 1’000.*

#### Relai AG: “Europe’s easiest Bitcoin investment app”
In the case of Relai AG, the startup is not directly regulated by FINMA, but indirectly via a self-regulatory organization (SRO). This is because the Anti-Money Laundering Act (AML) stipulates that financial intermediaries must join an SRO organized under private law to monitor compliance with due diligence requirements to prevent and avoid money laundering. One major advantage for Relai’s clients is that they can use the app and invest in Bitcoin without registration or verification if the daily investment amount does not exceed CHF 1,000 and/or the annual investment amount does not exceed CHF 100,000. This is the key to Relai’s attractiveness and success, as most of its younger clientele can start investing within a few minutes. However, a slowly growing portion of Relai's customers exceed the above investment amounts which then requires a registration. The startup was therefore indirectly forced to acquire a broker license in order to circumvent the recently introduced changes regarding the lowering of the threshold for cryptocurrency exchanges and thus maintain its attractiveness for its clients.

Liniger also explicitly emphasized in our interview that the fact that Switzerland has such lax regulation regarding cryptocurrencies made it possible to found their startup in the first place. According to Liniger, the regulatory situation in Switzerland is unique compared to other European countries. This might be an indication that regulation is indeed an important factor for the innovative power of the startup scene. In particular, if we compare the two industries of asset management and cryptocurrencies, in the latter we can see that more and more fintechs are emerging. Liniger also goes on to say that he personally appreciates the fact that in Switzerland, new regulations are not introduced from one day to the next, but rather take a long time, so that the industry has enough time to adjust. He would even go so far as to say that this is an advantage that Switzerland has compared to other European countries. He also mentions that he thinks Switzerland is very innovation friendly and he really appreciates the sandbox environment. Also, most fintechs in the crypto industry do not need a full banking license, but FINMA offers "light versions". 

#### House of Satoshi: “Home of Bitcoin”
*Rino Borini is co-founder and CEO of Scarossa, an independent consulting and media company, and the House of Satoshi, a store for crypto currencies located in Zurich where you can, among other things, convert crypto currencies into currencies. In the fall of 2020, the business magazine BILANZ named Borini one of the Digital Shapers, i.e. the 100 most important minds driving digitalization in the country. Rino Borini is also chairman of the board of directors at digital asset manager Descartes Finance. Moreover, he is also the course director for the "Digital Finance" and "Digital Insurance" courses at HWZ Zurich.*

He starts our interview by asserting that he sees no difference between traditional banks and fintech startups when it comes to regulation in Switzerland. He thinks that with fintech licensing and sandboxes, an environment has been created that could actually foster innovation. But when he hears from startups how long it takes to get a license, which is the basic requirement for a startup to get started, he gets extremely frustrated. He strongly believes that the licensing process needs to be massively accelerated on the one hand, and also simplified on the other.

Borini further explains that he likes the regulations in the crypto industry as, compared internationally, Switzerland has one of the most modern DLT laws. So Switzerland does have the opportunity to develop exciting technologies in the crypto economy. But then, at the same time, he also sees circumstances that clearly hinder innovation in Switzerland: On the one hand, FINMA, which seems to violate technology neutrality, as FINMA does not necessarily regulate crypto and fintech identically, and on the other hand, traditional banks, which do not want to help crypto startups. To back up his criticism towards technology neutrality, he mentions the example of the CHF 1,000 limit for cryptocurrencies, "If I go to the traditional ATM, I can withdraw CHF 5,000 per day, but with crypto ATMs I now have a limit of CHF 1,000. So fiat money is treated differently than cryptocurrency," Borini says. This ultimately leads to innovation dampening on the one hand and also does not fit with the slogan "Blockchain Nation Switzerland." Further, he adds that it is extremely difficult for crypto startups to find a partner bank. Even just opening an account can be very difficult. “Not because it's not legally possible, but because banks simply don't want it”, according to Borini. He also hopes that FINMA will set a framework for DeFi (Decentralized Finance) as soon as possible. Otherwise, Switzerland should soon stop calling itself "Blockchain Nation Switzerland”. 

Regarding the question of what Switzerland should do in terms of regulations to promote innovation, Borino answers that with wealth tech and crypto, Switzerland has great potential to maintain a leading role internationally. In particular, he wishes Swiss citizens had more knowledge about the technologies and the potentials associated with them. According to Borino, we should have a different mindset: Not "yes, but..." but "yes, why not?" Regulators should also work much more closely with industries. Similarly, regulations should be updated much more often and adapted to circumstances. Borino believes that FINMA should not innovate the industry itself, but simply allow it. And likewise, FINMA needs a power team with leaders from the industry and the community who understand the technology and potential and actively listen to startups to identify problems. And finally, according to Borini, there should be a "fast lane," like at the airport, for the startups that have everything ready to go, so to speak, and could get going, have a good business model, and comply with laws and regulations. This way, these startups can quickly get a license and start doing business. 
